= AtCoder Gradle Plugin
:toc: left


== Introduction

https://atcoder.jp[AtCoder] tool for Gradle

This tool is inspired by https://github.com/Tatamo/atcoder-cli[atcoder-cli]

== Getting Started

Two Credentials is required

- GitHub Account to download from GitHub Packages Repository
- AtCoder Account

GitHub Account will be not need in future release.

:sourcedir: ../sample/getting-started

.build.gradle.kts
[source, kotlin]
----
include::{sourcedir}/build.gradle.kts[lines=1..3]
----

.setting.gradle.kts
[source, kotlin]
----
include::{sourcedir}/settings.gradle.kts[lines=1..31]
----

GitHub Package Credential use values saved `~/.gradle.properties`
this property key name is based on repository name in settings.gradle.kts

----
GithubPackagesAtCoderGradlePluginUsername={your github username}
GithubPackagesAtCoderGradlePluginPassword={your github personal access token start with "ghp_"}
----

AtCoder credentials will use values saved in  `~/.gradle.properties`

----
atcoderUsername={your atcoder username}
atcoderPassword={your atcoder password}
----

=== Login

----
$ gradle atcoderLogin
----

=== Create Contest Project

If you didn't execute login task,  login task  will execute automatically.

----
$ gradle atcoderNew --contest=practice
----

Now, the projects will create into 'subprojects/contests'

=== Solve It

----
subprojects/contests/practice/src/A/kotlin/main.kt
----

=== Submit

----
$ gradle :practice:atcoderSubmitA
----

== plugins

=== Main Plugins

==== atcoder

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder")
}
----

==== contest

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.contest")
}
----

=== Other Convention Plugins

Utils for Main or Language Convention Plugin.

==== kotlin

apply plugin and set atcoder env kotlin version and api level.

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.contest.kotlin")
}
----