= AtCoder Gradle Plugin
:toc: left


== Introduction

https://atcoder.jp[AtCoder] tool for Gradle

This tool is inspired by https://github.com/Tatamo/atcoder-cli[atcoder-cli]

== Getting Started

Two Credential is required

- GitHub Account to download from GitHub Packages Repository
- AtCoder Account

:sourcedir: ../sample/getting-started

.build.gradle.kts
[source, kotlin]
----
include::{sourcedir}/build.gradle.kts[lines=1..3]
----

.setting.gradle.kts
[source, kotlin]
----
include::{sourcedir}/settings.gradle.kts[lines=1..31]
----

GitHub Package Credential use values saved  ~/.gradle.properties
this property key name is based on repository name in settings.gradle.kts

----
GithubPackagesAtCoderGradlePluginUsername={user github username}
GithubPackagesAtCoderGradlePluginPassword={user github personal access token start with "ghp_"}
----

AtCoder credentials use values saved with
https://github.com/etiennestuder/gradle-credentials-plugin[gradle-credential-plugin]

----
$ gradle addCredentials --key atcoder.username --value {user atcoder username}
$ gradle addCredentials --key atcoder.password --value {user atcoder password}
----

=== Login

----
$ gradle atcoderLogin
----

=== Create Contest Project

If you didn't execute login task,  login task  will execute automatically.

----
$ gradle atcoderNew --contest=practice
----

Now, the projects will create into 'subprojects/contests'

=== Solve It

----
subprojects/contests/practice/src/A/kotlin/main.kt
----

=== Submit

----
$ gradle :practice:atcoderSubmitA
----

== plugins

=== Main Plugins

==== atcoder

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder")
}
----

==== contest

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.contest")
}
----



=== Language Convention Plugins

Setup Language Environment

==== kotlin

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.kotlin")
}
----


==== java

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.java")
}
----



=== Other Convention Plugins

Utils for Main or Language Convention Plugin.

==== credentials



.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.credentials")
}
----

==== auto-include

Setting plugin to add generated contest project automatically.

.settings.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.auto-include")
}
----


==== jvm

JVM Based Language Setup util plugin

.build.gradle.kts
[source, kotlin]
----
plugins {
    id("com.nisecoder.gradle.atcoder.jvm")
}
----
