name: "Check"

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Check
        uses: gradle/gradle-build-action@v1
        with:
          arguments: check
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
