name: "Check"

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up Java
        uses: actions/setup-java@v4.2.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: build
          gradle-home-cache-cleanup: true

      - name: Output Test Results to Summary
        uses: mikepenz/action-junit-report@v4.1.0
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/*.xml'