name: "Check"

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: build
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit

      - name: Output Test Results to Summary
        uses: mikepenz/action-junit-report@v4.0.3
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/*.xml'