name: "Check"

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 19 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Set up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Check
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: check

      - name: Save JUnit Result
        if: failure()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: junit
          path: build/reports/tests/
