name: "Check"

on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17, 21 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v4.1.5

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2

      - name: Build
        run: ./gradlew build

      - name: Output Test Results to Summary
        uses: mikepenz/action-junit-report@v4.2.1
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/*.xml'