name: "Validate Gradle Wrapper"

on: pull_request

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: gradle/actions/wrapper-validation@v3.3.2
