name: "Publish Documents"

on:
  push:
    tags: [ "v*" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0

      - name: Set up Java for Publishing
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate Document
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: asciidoctor
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
        env:
          ORG_GRADLE_PROJECT_publishVersion: ${{ github.ref }}

      - name: Upload Document Artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: build/docs/asciidoc

      - name: Deploy Document
        uses: actions/deploy-pages@v2.0.4
