name: "Publishing Documents"

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java for Publishing
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Generate Document
        uses: gradle/gradle-build-action@v1
        with:
          arguments: asciidoctor
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true

      - name: Publish Document to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/docs/asciidoc
