name: "Publish Artifacts"

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up Java for Publishing
        uses: actions/setup-java@v4.1.0
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Publish to Github Packages
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_publishVersion: ${{ github.ref }}
          ORG_GRADLE_PROJECT_gitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_gitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
