name: "Publish Artifacts"

on:
  push:
    tags: [ "v*" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4

      - name: Setup Java for Publishing
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2

      - name: Publish to Github Packages
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_publishVersion: ${{ github.ref }}
          ORG_GRADLE_PROJECT_gitHubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_gitHubPackagesPassword: ${{ secrets.GITHUB_TOKEN }}
